### ISSUE TITLE
A way to export the diagram

### ISSUE THREAD

**Issue by gparradob** [Mini-Stef/Core-Data-Model-Editor#1]
**Is your feature request related to a problem? Please describe.**
Trying to see the whole diagram is hard and the only way to see it is to print it, but it doesn't print for some reason

**Describe the solution you'd like**
An option to export a JPG, PNG, or even an svg of the diagram

**Describe alternatives you've considered**
There's no other way, not even another app or service

**Additional context**

**Comment by Mini-Stef** [comment]
Hello,
Thank for your comment, that's my first one :-)
If I understand correctly, you ask for a "way to export the diagram". I guess that's the graphical view of the entities and their relations.
Which format would you like to have ?

For the time being (revision 1.1 of the app), you can print (from the File menu), and in the print dialog, you can export to a PDF file.

If you wish other export format, I can have a look (currently working on "undo")..

**Comment by gparradob** [comment]
Hi. I tried printing, but it "prints" the pdf on white color on a white background.
![Screenshot 2023-11-21 at 9 37 45 AM](https://github.com/Mini-Stef/Core-Data-Model-Editor/assets/129098063/1e925c26-558a-42b0-bd92-6620ebc56d8f)

**Comment by gparradob** [comment]
Trying different things I found it prints with the right colors when in light mode, but another problem is present, that's why printing is not a viable solution.
My database is quite complex and it's bigger than what the zoom can accomplish, and this prints only what is visible at the moment of printing so it's incomplete. Either expanding the zoom out capabilities, or printing the whole view even if it's not visible would work for this case.

**Comment by Mini-Stef** [comment]
OK, so thank you for discovering all this.
If I summarize (just a list, no priority meant) : 
* While printing, there is a problem in dark mode (white over white)
* Printing prints only the visible part of the window (which is a problem for huge diagrams)
* You'd like to have more capacity in the zoom
* You'd like to export to PNG

Well, good list :-)

Note that I am unsure how to split the model into pages in a smart way, you may have to move the entities so that the page cut does not fall in the middle of them. So it might be handy if I draw light page limits on the canvas so you can position your entities.
Any better idea ?

Also, would you be allowed/OK to send me your data model ? It is always nice to have real life examples.
No obligation, of course.

Many thanks again.

**Comment by gparradob** [comment]
Holy!! That was huge. Thanks.
